apiVersion: apps/v1
kind: Deployment
metadata:
  name: kioque-frontend
  namespace: default
  labels:
    app: kioque-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kioque-frontend
  template:
    metadata:
      labels:
        app: kioque-frontend
    spec:
      containers:
      - name: frontend
        image: 276713244047.dkr.ecr.us-east-1.amazonaws.com/kioque-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 