apiVersion: v1
kind: Service
metadata:
  name: kioque-frontend-service
  namespace: default
  labels:
    app: kioque-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: kioque-frontend 